<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2AHC2yK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2AHC2yK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2AHC2yK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2AHC2yK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2AHC2yK\App_KernelDevDebugContainer([
    'container.build_hash' => '2AHC2yK',
    'container.build_id' => '6b6a11de',
    'container.build_time' => 1674392959,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2AHC2yK');
